### PR TITLE
Feature/vaadin 8

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Migrated project to Maven and Vaadin 8.

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Hello.
I've ported this add-on to Vaadin 8 and Maven.
Can you please review the request and release the new addon version, if everything's ok?

**Comment by tehapo** [comment]
Thanks @SomeoneToIgnore! I'll try to find some time to review this next week.

**Comment by tehapo** [comment]
LGTM! Thanks!

**Comment by SomeoneToIgnore** [comment]
Awesome! Waiting for the new version of the add-on then :)

**Comment by SomeoneToIgnore** [comment]
@tehapo speaking of the add-on release, can you, please, release it in the nearby future? 
I would like to use it in the project and will really appreciate the quick release :)

**Comment by tehapo** [comment]
@SomeoneToIgnore Sure, I'll upload a release later today.

**Comment by SomeoneToIgnore** [comment]
Thanks!

**Comment by tehapo** [comment]
Relased a new version `3.0-beta1`

**Pull request merged**
